COPY INTO @TST_DATAMART_DB.STANDARD_OUT.DIH_EXCG_EXTERNAL_OUTBOUND_STAGE/TST_RAW_INBOUND_DB_CEDAR_GATE_RESP_ELIGIBILITY_DYN.sql

FROM (

SELECT
'CREATE OR REPLACE DYNAMIC TABLE AS TST_RAW_INBOUND_DB.CEDAR_GATE_RESP.ELIGIBILITY_DYN \n TARGET_LAG = DOWNSTREAM \n WAREHOUSE  = TST_ELT_STD_WH \n REFRESH_MODE = AUTO \n AS \n SELECT  '|| ARRAY_TO_STRING( ARRAY_AGG(  COLUMN_NAME || ' AS ' || COLUMN_ALIAS ) WITHIN GROUP (ORDER BY ORDINAL_POSITION),',') ||'\n FROM \n PRD_AR_INBOUND_DB.CEDAR_GATE.ELIGIBILITY' AS DYN_TABLE_SQL
FROM  (SELECT B.TABLE_NAME,B.COLUMN_NAME,B.ORDINAL_POSITION , NVL(A.ABCBS_FIELD_DESC ,B.COLUMN_NAME) AS COLUMN_ALIAS FROM
 (SELECT TABLE_NAME,COLUMN_NAME,ORDINAL_POSITION FROM PRD_AR_INBOUND_DB.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA  = 'CEDAR_GATE' AND
 TABLE_NAME IN (SELECT DISTINCT TABLE_NAME FROM PRD_RAW_INBOUND_DB.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA  LIKE '%CEDAR_GATE%' )
 ORDER BY TABLE_NAME,ORDINAL_POSITION) B
LEFT JOIN   PRD_AR_INBOUND_DB.CEDAR_GATE.EXTRACT_FIELD_NAMES A
  ON A.TABLE_NAME = B.TABLE_NAME AND A.EXTRACT_FIELD_NAME = B.COLUMN_NAME
  WHERE B.TABLE_NAME = 'ELIGIBILITY'  
  ORDER BY B.TABLE_NAME,B.ORDINAL_POSITION )

GROUP BY TABLE_NAME)

FILE_FORMAT = (TYPE = CSV , COMPRESSION = NONE , RECORD_DELIMITER = NONE , FIELD_DELIMITER = NONE)

HEADER = FALSE

SINGLE = TRUE

OVERWRITE= TRUE;

ALTER TABLE DEV_RAW_INBOUND_DB.CEDAR_GATE_RESP.ELIGIBILITY_TEMP RENAME COLUMN MBR_ID TO MEMBER_ID;



