-----------DEV-----------
--USE ROLE CDP_DEV_SYSADMIN_FR;
--USE DATABASE DEV_DATAMART_DB;

-----------TST-----------
--USE ROLE CDP_TST_SYSADMIN_FR;
--USE DATABASE TST_DATAMART_DB;

-----------UAT-----------
--USE ROLE CDP_UAT_SYSADMIN_FR;
--USE DATABASE UAT_DATAMART_DB;

-----------PRD-----------
--USE ROLE CDP_PRD_SYSADMIN_FR;
--USE DATABASE PRD_DATAMART_DB;

alter table PRIMARY_CARE.CHI_COMBINED set CHANGE_TRACKING = TRUE;

CREATE OR REPLACE DYNAMIC TABLE PRIMARY_CARE.CHI_DEMOG_DYN
 TARGET_LAG = '1 day'
  WAREHOUSE = PRD_ELT_STD_WH
  AS
(
    SELECT        
CHI_DATA_POINT, 
CHI_DATA_POINT_REF,
MBR_GRP , 
MASTER_PCP,
MASTER_CLINIC,
COUNT( CONCAT(CONTRACT_ID, PARTY_KEY)) AS CNT_OF_MEMBERID , 
CAST(AVG(AGE) AS DECIMAL(6,3)) AS AVG_AGE, 
CAST(SUM( CASE WHEN MBR_GENDER_CD = 'M' THEN 1 ELSE 0 END) AS INTEGER) AS MALE_CNT ,
CAST(SUM( CASE WHEN MBR_GENDER_CD = 'F' THEN 1 ELSE 0 END) AS INTEGER) AS FEMALE_CNT,
CAST(CAST( SUM( CASE WHEN MBR_GENDER_CD = 'M' THEN 1 ELSE 0 END) AS DECIMAL(10,4))/COUNT( CONCAT(CONTRACT_ID, PARTY_KEY))*100 AS DECIMAL(6,3))  AS MALE_PCT ,
CAST(CAST( SUM( CASE WHEN MBR_GENDER_CD = 'F' THEN 1 ELSE 0 END) AS DECIMAL(10,4))/COUNT( CONCAT(CONTRACT_ID, PARTY_KEY))*100 AS DECIMAL(6,3))  AS FEMALE_PCT ,

SUM(CASE WHEN MBR_GRP != 'Self Funded' and SOURCE_CODE <> 'IH' THEN RETRO_RISK ELSE DX_MED_RISK END * YTD_MM) /SUM(YTD_MM) AS YTD_ADJUSTED_RETRO_RISK, --MM_ADJUSTED_RETRO_RISK, 
SUM(PROSP_RISK * YTD_MM)/SUM(YTD_MM) AS YTD_ADJUSTED_PROSP_RISK, --MM_ADJUSTED_PROSP_RISK ,

SUM(CASE WHEN MBR_GRP != 'Self Funded' and SOURCE_CODE <> 'IH' THEN RETRO_RISK ELSE DX_MED_RISK END * RY_MM) /SUM(RY_MM) AS RY_ADJUSTED_RETRO_RISK, --MM_ADJUSTED_RETRO_RISK, 
SUM(PROSP_RISK * RY_MM)/SUM(RY_MM) AS RY_ADJUSTED_PROSP_RISK, --MM_ADJUSTED_PROSP_RISK ,


ALIGN_AS_OF_DT,
CAST(CURRENT_DATE AS DATE) AS LOAD_DT
FROM  PRIMARY_CARE.CHI_COMBINED 
GROUP BY  CHI_DATA_POINT, CHI_DATA_POINT_REF , MBR_GRP , ALIGN_AS_OF_DT ,MASTER_PCP, MASTER_CLINIC

UNION

SELECT        
CHI_DATA_POINT, 
CHI_DATA_POINT_REF, 
MBR_GRP ,
'TOTAL' AS MASTER_PCP,
'TOTAL' AS MASTER_CLINIC,
COUNT( CONCAT(CONTRACT_ID, PARTY_KEY)) AS COUNT_OF_MEMBERID , 
CAST(AVG(AGE) AS DECIMAL(6,3)) AS AVG_AGE, 
CAST(SUM( CASE WHEN MBR_GENDER_CD = 'M' THEN 1 ELSE 0 END) AS INTEGER) AS MALE_CNT ,
CAST(SUM( CASE WHEN MBR_GENDER_CD = 'F' THEN 1 ELSE 0 END) AS INTEGER) AS FEMALE_CNT,
CAST(CAST( SUM( CASE WHEN MBR_GENDER_CD = 'M' THEN 1 ELSE 0 END) AS DECIMAL(10,4))/COUNT( CONCAT(CONTRACT_ID, PARTY_KEY))*100 AS DECIMAL(6,3))  AS MALE_PCT ,
CAST(CAST( SUM( CASE WHEN MBR_GENDER_CD = 'F' THEN 1 ELSE 0 END) AS DECIMAL(10,4))/COUNT( CONCAT(CONTRACT_ID, PARTY_KEY))*100 AS DECIMAL(6,3)) AS FEMALE_PCT ,

SUM(CASE WHEN MBR_GRP != 'Self Funded' and SOURCE_CODE <> 'IH' THEN RETRO_RISK ELSE DX_MED_RISK END * YTD_MM) /SUM(YTD_MM) AS YTD_ADJUSTED_RETRO_RISK, --MM_ADJUSTED_RETRO_RISK, 
SUM(PROSP_RISK * YTD_MM)/SUM(YTD_MM) AS YTD_ADJUSTED_PROSP_RISK, --MM_ADJUSTED_PROSP_RISK ,
SUM(CASE WHEN MBR_GRP != 'Self Funded' and SOURCE_CODE <> 'IH' THEN RETRO_RISK ELSE DX_MED_RISK END * RY_MM) /SUM(RY_MM) AS RY_ADJUSTED_RETRO_RISK, --MM_ADJUSTED_RETRO_RISK, 
SUM(PROSP_RISK * RY_MM)/SUM(RY_MM) AS RY_ADJUSTED_PROSP_RISK, --MM_ADJUSTED_PROSP_RISK ,

ALIGN_AS_OF_DT,
CAST(CURRENT_DATE AS DATE) AS LOAD_DT
FROM  PRIMARY_CARE.CHI_COMBINED 
GROUP BY  CHI_DATA_POINT, CHI_DATA_POINT_REF  , ALIGN_AS_OF_DT,MBR_GRP

UNION


SELECT        
CHI_DATA_POINT, 
CHI_DATA_POINT_REF, 
'TOTAL'  AS MBR_GRP  ,
'TOTAL' AS MASTER_PCP,
'TOTAL' AS MASTER_CLINIC,
COUNT( CONCAT(CONTRACT_ID, PARTY_KEY)) AS COUNT_OF_MEMBERID , 
CAST(AVG(AGE) AS DECIMAL(6,3)) AS AVG_AGE, 
CAST(SUM( CASE WHEN MBR_GENDER_CD = 'M' THEN 1 ELSE 0 END) AS INTEGER) AS MALE_CNT ,
CAST(SUM( CASE WHEN MBR_GENDER_CD = 'F' THEN 1 ELSE 0 END) AS INTEGER) AS FEMALE_CNT,
CAST(CAST( SUM( CASE WHEN MBR_GENDER_CD = 'M' THEN 1 ELSE 0 END) AS DECIMAL(10,4))/COUNT( CONCAT(CONTRACT_ID, PARTY_KEY))*100 AS DECIMAL(6,3))  AS MALE_PCT ,
CAST(CAST( SUM( CASE WHEN MBR_GENDER_CD = 'F' THEN 1 ELSE 0 END) AS DECIMAL(10,4))/COUNT( CONCAT(CONTRACT_ID, PARTY_KEY))*100 AS DECIMAL(6,3)) AS FEMALE_PCT ,

SUM(CASE WHEN MBR_GRP != 'Self Funded' and SOURCE_CODE <> 'IH' THEN RETRO_RISK ELSE DX_MED_RISK END * YTD_MM) /SUM(YTD_MM) AS YTD_ADJUSTED_RETRO_RISK, --MM_ADJUSTED_RETRO_RISK, 
SUM(PROSP_RISK * YTD_MM)/SUM(YTD_MM) AS YTD_ADJUSTED_PROSP_RISK, --MM_ADJUSTED_PROSP_RISK ,
SUM(CASE WHEN MBR_GRP != 'Self Funded' and SOURCE_CODE <> 'IH' THEN RETRO_RISK ELSE DX_MED_RISK END * RY_MM) /SUM(RY_MM) AS RY_ADJUSTED_RETRO_RISK, --MM_ADJUSTED_RETRO_RISK, 
SUM(PROSP_RISK * RY_MM)/SUM(RY_MM) AS RY_ADJUSTED_PROSP_RISK, --MM_ADJUSTED_PROSP_RISK ,


ALIGN_AS_OF_DT,
CAST(CURRENT_DATE AS DATE) AS LOAD_DT
FROM  PRIMARY_CARE.CHI_COMBINED 
GROUP BY  CHI_DATA_POINT, CHI_DATA_POINT_REF  , ALIGN_AS_OF_DT



);


comment on table PRIMARY_CARE.CHI_DEMOG_DYN is 'CHI Member lelvel Demographic Information';



