-----------DEV-----------
--USE ROLE CDP_DEV_SYSADMIN_FR;
--USE DATABASE DEV_DATAMART_DB;

-----------TST-----------
--USE ROLE CDP_TST_SYSADMIN_FR;
--USE DATABASE TST_DATAMART_DB;

-----------UAT-----------
--USE ROLE CDP_UAT_SYSADMIN_FR;
--USE DATABASE UAT_DATAMART_DB;

-----------PRD-----------
--USE ROLE CDP_PRD_SYSADMIN_FR;
--USE DATABASE PRD_DATAMART_DB;

alter table PRIMARY_CARE.CHI_COMBINED set CHANGE_TRACKING = TRUE;
alter table PRIMARY_CARE.CHI_COST_MBR_LEVEL set CHANGE_TRACKING = TRUE;

CREATE OR REPLACE DYNAMIC TABLE PRIMARY_CARE.CHI_SVC_CAT_PMPM_DYN
 TARGET_LAG = '1 day'
  WAREHOUSE = DEV_ELT_STD_WH
  AS 
(
WITH 
--  MM Calculation on CHI Level 
CHI_MM_TOT AS 
(SELECT   CHI_DATA_POINT,
         CHI_DATA_POINT_REF,
         ALIGN_AS_OF_DT AS ALIGN_AS_OF_DT,
         SUM(YTD_MM)AS YTD_MM,
         SUM(RY_MM) AS RY_MM
FROM     PRIMARY_CARE.CHI_COMBINED
GROUP BY CHI_DATA_POINT, CHI_DATA_POINT_REF, ALIGN_AS_OF_DT),

-- 

SVC_CAT_SUMS AS (
SELECT  CHI_CML.CHI_DATA_POINT,
         CHI_CML.CHI_DATA_POINT_REF,
         CHI_CML.SVC_CAT,
         'TOTAL' AS SVC_SUB_CAT,
         'TOTAL' AS MASTER_PCP,
         'TOTAL' AS MBR_GRP,
         CHI_CML.ALIGN_AS_OF_DT,
         SUM(RY_ALLOWED_AMT) RY_ALLOWED_AMT,
         MAX(CHI_MM.RY_MM) RY_MM,
         SUM(RY_ALLOWED_AMT) /MAX(CHI_MM.RY_MM) AS RY_PMPM,
         SUM(YTD_ALLOWED_AMT) YTD_ALLOWED_AMT,
         MAX(CHI_MM.YTD_MM) YTD_MM,
         SUM(YTD_ALLOWED_AMT) /MAX(CHI_MM.YTD_MM) AS YTD_PMPM
FROM     PRIMARY_CARE.CHI_COST_MBR_LEVEL CHI_CML 
         JOIN CHI_MM_TOT CHI_MM ON CHI_CML.CHI_DATA_POINT = CHI_MM.CHI_DATA_POINT 
         AND CHI_CML.CHI_DATA_POINT_REF = CHI_MM.CHI_DATA_POINT_REF 
         AND CHI_CML.ALIGN_AS_OF_DT = CHI_MM.ALIGN_AS_OF_DT
GROUP BY CHI_CML.CHI_DATA_POINT, CHI_CML.CHI_DATA_POINT_REF, CHI_CML.SVC_CAT, 
         CHI_CML.ALIGN_AS_OF_DT),


SVC_SUB_CAT_SUMS AS (
SELECT  CHI_CML.CHI_DATA_POINT,
         CHI_CML.CHI_DATA_POINT_REF,
         CHI_CML.SVC_CAT,
         SVC_SUB_CAT AS SVC_SUB_CAT,
         'TOTAL' AS MASTER_PCP,
         'TOTAL' AS MBR_GRP,
         CHI_CML.ALIGN_AS_OF_DT,
         SUM(RY_ALLOWED_AMT) RY_ALLOWED_AMT,
         MAX(CHI_MM.RY_MM) RY_MM,
         SUM(RY_ALLOWED_AMT) /MAX(CHI_MM.RY_MM) AS RY_PMPM,
         SUM(YTD_ALLOWED_AMT) YTD_ALLOWED_AMT,
         MAX(CHI_MM.YTD_MM) YTD_MM,
         SUM(YTD_ALLOWED_AMT) /MAX(CHI_MM.YTD_MM) AS YTD_PMPM
FROM     PRIMARY_CARE.CHI_COST_MBR_LEVEL CHI_CML 
         JOIN CHI_MM_TOT CHI_MM ON CHI_CML.CHI_DATA_POINT = CHI_MM.CHI_DATA_POINT 
         AND CHI_CML.CHI_DATA_POINT_REF = CHI_MM.CHI_DATA_POINT_REF 
         AND CHI_CML.ALIGN_AS_OF_DT = CHI_MM.ALIGN_AS_OF_DT
GROUP BY CHI_CML.CHI_DATA_POINT, CHI_CML.CHI_DATA_POINT_REF, CHI_CML.SVC_CAT ,CHI_CML.SVC_SUB_CAT, 
         CHI_CML.ALIGN_AS_OF_DT),


--  MM Calculation on CHI- MBR_GRP Level 

CHI_MM_MBR_GRP AS 
(SELECT   CHI_DATA_POINT,
         CHI_DATA_POINT_REF,
         ALIGN_AS_OF_DT AS ALIGN_AS_OF_DT,
         SUM(YTD_MM)AS YTD_MM,
         SUM(RY_MM) AS RY_MM,
         MBR_GRP
FROM     PRIMARY_CARE.CHI_COMBINED
GROUP BY CHI_DATA_POINT, CHI_DATA_POINT_REF, ALIGN_AS_OF_DT,MBR_GRP),


SVC_CAT_SUMS_MBR_GRP AS 
(SELECT  CHI_CML.CHI_DATA_POINT,
         CHI_CML.CHI_DATA_POINT_REF,
         CHI_CML.SVC_CAT,
         'TOTAL' AS SVC_SUB_CAT,
         'TOTAL' AS MASTER_PCP,
          CHI_CML.MBR_GRP,
         CHI_CML.ALIGN_AS_OF_DT,
         SUM(RY_ALLOWED_AMT) RY_ALLOWED_AMT,
         MAX(CHI_MM.RY_MM) RY_MM,
         SUM(RY_ALLOWED_AMT) /MAX(CHI_MM.RY_MM) AS RY_PMPM,
         SUM(YTD_ALLOWED_AMT) YTD_ALLOWED_AMT,
         MAX(CHI_MM.YTD_MM) YTD_MM,
         SUM(YTD_ALLOWED_AMT) /MAX(CHI_MM.YTD_MM) AS YTD_PMPM
FROM     PRIMARY_CARE.CHI_COST_MBR_LEVEL CHI_CML 
         JOIN CHI_MM_MBR_GRP CHI_MM ON CHI_CML.CHI_DATA_POINT = CHI_MM.CHI_DATA_POINT 
         AND CHI_CML.CHI_DATA_POINT_REF = CHI_MM.CHI_DATA_POINT_REF 
         AND CHI_CML.ALIGN_AS_OF_DT = CHI_MM.ALIGN_AS_OF_DT
         AND CHI_CML.MBR_GRP = CHI_MM.MBR_GRP 
          GROUP BY CHI_CML.CHI_DATA_POINT, CHI_CML.CHI_DATA_POINT_REF, CHI_CML.SVC_CAT, 
         CHI_CML.ALIGN_AS_OF_DT,CHI_CML.MBR_GRP),


--  MM Calculation on CHI- PCP Level 

CHI_MM_PCP AS 
(SELECT   CHI_DATA_POINT,
         CHI_DATA_POINT_REF,
         ALIGN_AS_OF_DT AS ALIGN_AS_OF_DT,
         SUM(YTD_MM)AS YTD_MM,
         SUM(RY_MM) AS RY_MM,
         MASTER_PCP
FROM     PRIMARY_CARE.CHI_COMBINED
GROUP BY CHI_DATA_POINT, CHI_DATA_POINT_REF, ALIGN_AS_OF_DT,MASTER_PCP),

SVC_CAT_SUMS_PCP AS 
(SELECT  CHI_CML.CHI_DATA_POINT,
         CHI_CML.CHI_DATA_POINT_REF,
         CHI_CML.SVC_CAT,
         'TOTAL' AS SVC_SUB_CAT,
         CHI_CML.MASTER_PCP,
         'TOTAL' AS MBR_GRP,
         CHI_CML.ALIGN_AS_OF_DT,
         SUM(RY_ALLOWED_AMT) RY_ALLOWED_AMT,
         MAX(CHI_MM.RY_MM) RY_MM,
         SUM(RY_ALLOWED_AMT) /MAX(CHI_MM.RY_MM) AS RY_PMPM,
         SUM(YTD_ALLOWED_AMT) YTD_ALLOWED_AMT,
         MAX(CHI_MM.YTD_MM) YTD_MM,
         SUM(YTD_ALLOWED_AMT) /MAX(CHI_MM.YTD_MM) AS YTD_PMPM
FROM     PRIMARY_CARE.CHI_COST_MBR_LEVEL CHI_CML 
         JOIN CHI_MM_PCP CHI_MM ON CHI_CML.CHI_DATA_POINT = CHI_MM.CHI_DATA_POINT 
         AND CHI_CML.CHI_DATA_POINT_REF = CHI_MM.CHI_DATA_POINT_REF 
         AND CHI_CML.ALIGN_AS_OF_DT = CHI_MM.ALIGN_AS_OF_DT
         AND CHI_CML.MASTER_PCP = CHI_MM.MASTER_PCP
         GROUP BY CHI_CML.CHI_DATA_POINT, CHI_CML.CHI_DATA_POINT_REF, CHI_CML.SVC_CAT, 
         CHI_CML.ALIGN_AS_OF_DT,CHI_CML.MASTER_PCP),


--  MM Calculation on CHI- MBR_GRP & PCP Level 

CHI_MM_PCP_MBR_GRP AS 
(SELECT   CHI_DATA_POINT,
         CHI_DATA_POINT_REF,
         ALIGN_AS_OF_DT AS ALIGN_AS_OF_DT,
         SUM(YTD_MM)AS YTD_MM,
         SUM(RY_MM) AS RY_MM,
         MBR_GRP,
         MASTER_PCP
FROM     PRIMARY_CARE.CHI_COMBINED
GROUP BY CHI_DATA_POINT, CHI_DATA_POINT_REF, ALIGN_AS_OF_DT,MBR_GRP,MASTER_PCP),


SVC_CAT_SUMS_PCP_MBR_GRP AS 
(SELECT  CHI_CML.CHI_DATA_POINT,
         CHI_CML.CHI_DATA_POINT_REF,
         CHI_CML.SVC_CAT,
         'TOTAL' AS SVC_SUB_CAT,
         CHI_CML.MASTER_PCP AS MASTER_PCP,
         CHI_CML.MBR_GRP AS MBR_GRP,
         CHI_CML.ALIGN_AS_OF_DT,
         SUM(RY_ALLOWED_AMT) RY_ALLOWED_AMT,
         MAX(CHI_MM.RY_MM) RY_MM,
         SUM(RY_ALLOWED_AMT) /MAX(CHI_MM.RY_MM) AS RY_PMPM,
         SUM(YTD_ALLOWED_AMT) YTD_ALLOWED_AMT,
         MAX(CHI_MM.YTD_MM) YTD_MM,
         SUM(YTD_ALLOWED_AMT) /MAX(CHI_MM.YTD_MM) AS YTD_PMPM
FROM     PRIMARY_CARE.CHI_COST_MBR_LEVEL CHI_CML 
         JOIN CHI_MM_PCP_MBR_GRP CHI_MM ON CHI_CML.CHI_DATA_POINT = CHI_MM.CHI_DATA_POINT 
         AND CHI_CML.CHI_DATA_POINT_REF = CHI_MM.CHI_DATA_POINT_REF 
         AND CHI_CML.ALIGN_AS_OF_DT = CHI_MM.ALIGN_AS_OF_DT
         AND CHI_CML.MBR_GRP = CHI_MM.MBR_GRP 
         AND CHI_CML.MASTER_PCP = CHI_MM.MASTER_PCP
     GROUP BY CHI_CML.CHI_DATA_POINT, CHI_CML.CHI_DATA_POINT_REF, CHI_CML.SVC_CAT, 
         CHI_CML.ALIGN_AS_OF_DT,CHI_CML.MASTER_PCP,CHI_CML.MBR_GRP)




-- SVC CAT Level SUMs
SELECT * FROM SVC_CAT_SUMS 
UNION 
SELECT * FROM SVC_SUB_CAT_SUMS 
UNION 
SELECT * FROM SVC_CAT_SUMS_MBR_GRP
UNION 
SELECT * FROM SVC_CAT_SUMS_PCP
UNION 
SELECT * FROM SVC_CAT_SUMS_PCP_MBR_GRP 
UNION 
-- CHI  Level SUMs 
SELECT   CHI_DATA_POINT,
         CHI_DATA_POINT_REF,
         'TOTAL' AS SVC_CAT,
         'TOTAL' AS SVC_SUB_CAT,
         'TOTAL' AS MASTER_PCP,
         'TOTAL' AS MBR_GRP,
         ALIGN_AS_OF_DT,
         SUM(RY_ALLOWED_AMT) RY_ALLOWED_AMT,
         MAX(RY_MM) RY_MM,
         SUM(RY_ALLOWED_AMT)/MAX(RY_MM) AS RY_PMPM,
         SUM(YTD_ALLOWED_AMT) YTD_ALLOWED_AMT,
         MAX(YTD_MM) YTD_MM,
         SUM(YTD_ALLOWED_AMT)/MAX(YTD_MM) AS YTD_PMPM
FROM     SVC_CAT_SUMS
GROUP BY CHI_DATA_POINT, CHI_DATA_POINT_REF, ALIGN_AS_OF_DT

);
comment on table PRIMARY_CARE.CHI_SVC_CAT_PMPM_DYN is 'Service categories per month per member';





