USE DATABASE ${SNOWFLAKE_ENV}_RAW_INBOUND_DB;
USE SCHEMA BCBSA;
USE WAREHOUSE ${SNOWFLAKE_ENV}_ELT_BIG_WH;


--DELETE FROM ${SNOWFLAKE_ENV}_DATAMART_DB.PROV.BCBSA_PDT_PROV_HIST;

CREATE OR REPLACE TEMPORARY TABLE 
PROV_TAX_ID AS 
SELECT DISTINCT FILE_RECORD_ID,PROV_TAX_ID,PROV_TAX_ID_TYPE FROM ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_PRACTITIONER 
WHERE FILE_EXPORT_TYPE = 'AnalyticsExportPII';

CREATE OR REPLACE TEMPORARY  TABLE PDT_FHIR_PRACTITIONER_ROLE_TEMP AS 
SELECT  
PR.FILE_RECORD_ID,
PR.FILE_EXPORT_TYPE,
PR.LAST_UPDTD_TS,
PR.VERSION_ID,
PR.PRACTITIONER_REF_RECORD_ID,
PR.NETWORK_REF_RECORD_ID,
PR.ORGANIZATION_REF_RECORD_ID,
PR.LOCATION_REF_RECORD_ID,
PR.LICENSEE_REF_RECORD_ID,
HEALTHCARE_SERVICE_REF_RECORD_ID,
PR.PROV_TYPE_CD,
PR.PROV_TYPE_DISPLAY,
PR.SPECIALTY_DISPLAY,
PR.PROV_ENTITY_TYPE_CD,
PR.PROV_ENTITY_TYPE_DISPLAY,
PR.PROV_EFF_DT,
PR.PROV_TERM_DT,
PR.PROV_CONTRACT_STATUS,
PR.ACCEPTING_NEW_PATIENTS_CD,
PR.DISPLAY_IND_PROV,
PR.PROV_AFFIL_TYPE,
PR.PROV_AFFIL_REF,
PR.PCP_IND_CD,
PCP_SELECTABILITY_CD,
PR.PATIENT_AGE_RANGE_LOW ,
PR.PATIENT_AGE_RANGE_HIGH,
PR.PROV_PATIENT_GENDER_LIMIT ,
PR.PROV_ACCEPTS_MEMBER_SELECT_ATTRIB_IND,
PR.VALUE_BASED_PROGRAM_ID,
PR.DAYS_OF_WEEK_AND_OFFICE_HOURS,
ROW_NUMBER() OVER(PARTITION BY PR.FILE_RECORD_ID,PR.FILE_EXPORT_TYPE,PR.PRACTITIONER_REF_RECORD_ID,PR.NETWORK_REF_RECORD_ID,
                               PR.LOCATION_REF_RECORD_ID,PR.LICENSEE_REF_RECORD_ID ORDER BY  VERSION_ID DESC ) AS ROW_NUM
FROM ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_PRACTITIONER_ROLE  PR WHERE PR.FILE_EXPORT_TYPE = '${BCBSA_FILE_EXPORT_TYPE}' AND  PR.LOCATION_REF_RECORD_ID NOT LIKE '%TLOC%' AND PR.LOCATION_REF_RECORD_ID NOT LIKE '%TFLOC%'
QUALIFY ROW_NUM = 1 ;


CREATE OR REPLACE TEMPORARY TABLE HLT_CARE_SVC AS 
SELECT PR.FILE_RECORD_ID AS FILE_RECORD_ID , HC.healthcare_service_type_cd ||':'|| HC.healthcare_service_type AS HLT_CARE_SVC_CD,
ROW_NUMBER() OVER (PARTITION BY PR.file_record_id  ORDER BY HC.file_record_id DESC ) AS ROW_NUM
FROM ( SELECT DISTINCT FILE_RECORD_ID, HEALTHCARE_SERVICE_REF_RECORD_ID, FILE_EXPORT_TYPE FROM  
       ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_PRACTITIONER_ROLE  WHERE FILE_EXPORT_TYPE = '${BCBSA_FILE_EXPORT_TYPE}') PR 
JOIN ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_HEALTHCARE_SERVICE HC 
ON  PR.FILE_EXPORT_TYPE = HC.FILE_EXPORT_TYPE AND PR.HEALTHCARE_SERVICE_REF_RECORD_ID = HC.FILE_RECORD_ID AND healthcare_service_type IS NOT NULL  
AND healthcare_service_type <> ''  QUALIFY  ROW_NUM <=4;


CREATE OR REPLACE TEMPORARY TABLE HLT_CARE_SVC_FINAL AS  
SELECT 
$1 AS FILE_RECORD_ID,
$2 AS PROVIDER_CHARACTERISTICS_CODE_1,
$3 AS PROVIDER_CHARACTERISTICS_CODE_2,
$4 AS PROVIDER_CHARACTERISTICS_CODE_3,
$5 AS PROVIDER_CHARACTERISTICS_CODE_4
FROM HLT_CARE_SVC PIVOT(MAX(HLT_CARE_SVC_CD) FOR ROW_NUM IN (1,2,3,4))  ;


CREATE OR REPLACE TEMPORARY TABLE   PDT_FHIR_PRACTITIONER_BOARD_CERTIFICATION AS 
SELECT DISTINCT FILE_EXPORT_TYPE,
    P.FILE_RECORD_ID, 
    SPLIT_PART(TAB.VALUE,':',1) AS TAXONOMY_CODE,
    SPLIT_PART(TAB.VALUE,':',2) AS BOARD_CERTIFICATION_IND
FROM ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_PRACTITIONER P, LATERAL  STRTOK_SPLIT_TO_TABLE(BOARD_CERTIFICATION_IND,'||') TAB 
WHERE FILE_EXPORT_TYPE = '${BCBSA_FILE_EXPORT_TYPE}'
ORDER BY FILE_RECORD_ID , TAXONOMY_CODE  ;


CREATE OR REPLACE TEMPORARY TABLE   PDT_FHIR_PRACTITIONER_TAXONOMY_DESC AS 
SELECT DISTINCT FILE_EXPORT_TYPE,
    P.FILE_RECORD_ID, 
    SPLIT_PART(TAB.VALUE,':',1) AS TAXONOMY_CODE,
    SPLIT_PART(TAB.VALUE,':',2) AS TAXONOMY_DESC
FROM ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_PRACTITIONER P, LATERAL  STRTOK_SPLIT_TO_TABLE(TAXONOMY_DESC,'\n') TAB 
WHERE FILE_EXPORT_TYPE = '${BCBSA_FILE_EXPORT_TYPE}'
ORDER BY FILE_RECORD_ID , TAXONOMY_CODE  ;



CREATE OR REPLACE TEMPORARY TABLE PDT_FHIR_PRACTITIONER_TAXONOMY AS 
SELECT  NVL(TAX_CERT.FILE_EXPORT_TYPE, TAX_CERT.FILE_EXPORT_TYPE) AS FILE_EXPORT_TYPE ,
        NVL(TAX_CERT.FILE_RECORD_ID, TAX_DESC.FILE_RECORD_ID) AS FILE_RECORD_ID ,
NVL(TAX_CERT.TAXONOMY_CODE, TAX_DESC.TAXONOMY_CODE)||':'||NVL(TAX_CERT.BOARD_CERTIFICATION_IND,'')||':'||NVL(TAX_DESC.TAXONOMY_DESC,'') AS TAXONOMY,

        ROW_NUMBER() OVER (PARTITION BY NVL(TAX_CERT.FILE_EXPORT_TYPE, TAX_CERT.FILE_EXPORT_TYPE),NVL(TAX_CERT.FILE_RECORD_ID, TAX_CERT.FILE_RECORD_ID) 
        ORDER BY TAX_CERT.BOARD_CERTIFICATION_IND desc, NVL(TAX_CERT.TAXONOMY_CODE, TAX_DESC.TAXONOMY_CODE)) AS ROW_NUM
FROM PDT_FHIR_PRACTITIONER_BOARD_CERTIFICATION  TAX_CERT 
  FULL JOIN 
 PDT_FHIR_PRACTITIONER_TAXONOMY_DESC TAX_DESC ON 

TAX_CERT.FILE_EXPORT_TYPE   = TAX_DESC.FILE_EXPORT_TYPE AND 
TAX_CERT.FILE_RECORD_ID     = TAX_DESC.FILE_RECORD_ID AND 
TAX_CERT.TAXONOMY_CODE      = TAX_DESC.TAXONOMY_CODE  ;

CREATE OR REPLACE TEMPORARY TABLE PDT_FHIR_PRACTITIONER_TAXONOMY_FINAL AS 
SELECT  FILE_EXPORT_TYPE,
        FILE_RECORD_ID,

        SPLIT_PART($3,':',1) AS TAXONOMY_CD_1 ,
        SPLIT_PART($3,':',2) AS TAXONOMY_1_BOARD_CERTIFICATION ,
        SPLIT_PART($3,':',3) AS TAXONOMY_DESC_1 ,

        SPLIT_PART($4,':',1) AS TAXONOMY_CD_2 ,
        SPLIT_PART($4,':',2) AS TAXONOMY_2_BOARD_CERTIFICATION ,
        SPLIT_PART($4,':',3) AS TAXONOMY_DESC_2 ,


        SPLIT_PART($5,':',1) AS TAXONOMY_CD_3 ,
        SPLIT_PART($5,':',2) AS TAXONOMY_3_BOARD_CERTIFICATION ,
        SPLIT_PART($5,':',3) AS TAXONOMY_DESC_3 ,


        SPLIT_PART($6,':',1) AS TAXONOMY_CD_4 ,
        SPLIT_PART($6,':',2) AS TAXONOMY_4_BOARD_CERTIFICATION ,
        SPLIT_PART($6,':',3) AS TAXONOMY_DESC_4 ,

        SPLIT_PART($7,':',1) AS TAXONOMY_CD_5 ,
        SPLIT_PART($7,':',2) AS TAXONOMY_5_BOARD_CERTIFICATION ,
        SPLIT_PART($7,':',3) AS TAXONOMY_DESC_5


FROM PDT_FHIR_PRACTITIONER_TAXONOMY PIVOT(MAX(TAXONOMY) FOR ROW_NUM IN (1,2,3,4,5))  ; --WHERE TAXONOMY_DESC_5 IS NOT NULL  ;

CREATE OR REPLACE TEMPORARY TABLE FHIR_ORG_NAME AS 
SELECT DISTINCT FILE_RECORD_ID , PROV_ORGANIZATION_NAME ,PLAN_PROV_ID FROM ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_ORGANIZATION WHERE FILE_EXPORT_TYPE = '${BCBSA_FILE_EXPORT_TYPE}';



/* Feb 2026 - Added Code for Provider Credential and License Details - START */

-- MAX/Latest record 

CREATE OR REPLACE TEMPORARY TABLE MAX_PDT_REC AS (SELECT FILE_RECORD_ID , SPLIT_PART(FILE_NAME,'/',3)  AS FILE_EXPORT_TYPE, MAX(FILE_LAST_MODIFIED) AS FILE_LAST_MODIFIED  , FILE_RESOURCE_TYPE
FROM ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR 
WHERE  SPLIT_PART(FILE_NAME, '/', 3) = '${BCBSA_FILE_EXPORT_TYPE}'    AND 
FILE_RESOURCE_TYPE IN ( 'Practitioner' ,'PractitionerRole' , 'Location')  GROUP BY FILE_RECORD_ID,FILE_EXPORT_TYPE,FILE_RESOURCE_TYPE) ;


-- Provider Email from  ( 'Practitioner' ,'PractitionerRole' , 'Location') 
CREATE OR REPLACE TEMPORARY TABLE PROV_EMAIL_TEMP AS 
SELECT --qualification,
DISTINCT SPLIT_PART(FILE_NAME, '/', 3) AS FILE_EXPORT_TYPE,A.FILE_RESOURCE_TYPE,
A.FILE_RECORD_ID AS FILE_RECORD_ID ,A.FILE_CONTENT_RAW:telecom AS TELECOM
FROM   ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR A  ,  MAX_PDT_REC B 

WHERE  A.FILE_RECORD_ID = B.FILE_RECORD_ID AND A.FILE_LAST_MODIFIED = B.FILE_LAST_MODIFIED AND SPLIT_PART(A.FILE_NAME, '/', 3)= B.FILE_EXPORT_TYPE
AND SPLIT_PART(FILE_NAME, '/', 3) = '${BCBSA_FILE_EXPORT_TYPE}'  
AND A.FILE_RESOURCE_TYPE IN ( 'Practitioner' ,'PractitionerRole' , 'Location')
AND A.FILE_CONTENT_RAW:telecom IS NOT NULL ;



CREATE OR REPLACE TEMPORARY TABLE PROV_EMAIL AS 
SELECT 
FILE_EXPORT_TYPE,FILE_RESOURCE_TYPE,
FILE_RECORD_ID,
TELECOM, 
TEL.value:system AS TYPE,
TEL.value:use AS USE,
TEL.value:value AS EMAIL
FROM PROV_EMAIL_TEMP
,lateral flatten(input=>TELECOM, outer=>true) TEL
WHERE TEL.value:system = 'email' ;





-- Provider Qualification Details from 'Practitioner'

CREATE OR REPLACE TEMPORARY TABLE PROV_QUAL AS 
SELECT --qualification,
FILE_RECORD_ID, MAX(PROV_LICENSE) AS PROV_LICENSE, MAX(PROV_LICENSE_STATE)  AS PROV_LICENSE_STATE, 
MAX(PROV_LICENSE_STATUS) AS PROV_LICENSE_STATUS ,  MAX(Provider_Credential) AS PROV_CREDENTIAL,
MAX(Provider_Credential_DISPLAY) AS PROV_CREDENTIAL_DISPLAY,
MAX(Provider_Credential_extension_Code) AS PROV_CREDENTIAL_EXTENSION_CODE,
MAX(Provider_Credential_TYPE) PROV_CREDENTIAL_TYPE,  
MAX(issuer_display) AS issuer_display,
MAX(issuer_org_ref ) AS issuer_org_ref

FROM (SELECT DISTINCT qualification.value AS qualification,
A.FILE_RECORD_ID, qualification_identifier.value:value AS PROV_LICENSE

,CASE WHEN qual_extension_code_extension_extension.value:url = 'whereValid' THEN qual_extension_code_extension_extension_valueCodeableConcept_coding.value:code  END AS PROV_LICENSE_STATE
,CASE WHEN qual_extension_code_extension_extension.value:url = 'status' THEN qual_extension_code_extension_extension.value:valueCode END AS PROV_LICENSE_STATUS

,qualification_code_coding.value:code  AS Provider_Credential 
,qualification_code_coding.value:display AS Provider_Credential_DISPLAY
,SPLIT_PART(qualification_code_coding.value:system,'/',-1) AS Provider_Credential_TYPE
,qualification.value:extension[0].valueCode AS Provider_Credential_extension_Code
,qualification.value:issuer.display AS issuer_display
,qualification.value:issuer.reference AS issuer_org_ref

FROM   ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR A  ,  MAX_PDT_REC B 

,lateral flatten(input=>FILE_CONTENT_RAW:qualification,outer=>true) qualification
,lateral flatten(input=>qualification.value:identifier,outer=>true) qualification_identifier
,lateral flatten(input=>qualification.value:code:coding,outer=>true) qualification_code_coding
,lateral flatten(input=>qualification.value:code:extension,outer=>true) qual_extension_code_extension
,lateral flatten(input=>qual_extension_code_extension.value:extension,outer=>true) qual_extension_code_extension_extension
,lateral flatten(input=>qual_extension_code_extension_extension.value:valueCodeableConcept:coding,outer=>true) qual_extension_code_extension_extension_valueCodeableConcept_coding
,lateral flatten(input=>qualification.value:extension,outer=>true) qual_extension_extension
WHERE  A.FILE_RECORD_ID = B.FILE_RECORD_ID AND A.FILE_LAST_MODIFIED = B.FILE_LAST_MODIFIED AND SPLIT_PART(FILE_NAME, '/', 3) = '${BCBSA_FILE_EXPORT_TYPE}'   AND B.FILE_RESOURCE_TYPE = 'Practitioner' AND  A.FILE_RESOURCE_TYPE = 'Practitioner'  
AND qualification IS NOT NULL 

) GROUP BY qualification,FILE_RECORD_ID;


CREATE OR REPLACE TEMPORARY TABLE PROV_QUAL_1 AS 
SELECT 
    FILE_RECORD_ID,
    ARRAY_AGG(  
        OBJECT_CONSTRUCT(
            'PROV_LICENSE', PROV_LICENSE,
            'PROV_LICENSE_STATE', PROV_LICENSE_STATE,
            'PROV_LICENSE_STATUS', PROV_LICENSE_STATUS
        )
    ) WITHIN GROUP (ORDER BY PROV_LICENSE_STATE ASC) AS PROV_LICENSES
FROM (
    SELECT DISTINCT
        FILE_RECORD_ID,
        UPPER(REPLACE(TRIM(PROV_LICENSE), ' ', '')) AS PROV_LICENSE,
        UPPER(TRIM(PROV_LICENSE_STATE)) AS PROV_LICENSE_STATE,
        UPPER(TRIM(PROV_LICENSE_STATUS)) AS PROV_LICENSE_STATUS
    FROM PROV_QUAL
    WHERE PROV_LICENSE IS NOT NULL
      AND TRIM(PROV_LICENSE) <> ''
)
GROUP BY FILE_RECORD_ID 
ORDER BY FILE_RECORD_ID;




/* Feb 2026 - Added Code for Provider Credential and License Details - END*/

CREATE OR REPLACE TEMPORARY TABLE BCBSA_PDT_PROV_HIST_TEMP1 AS 
SELECT 
PR.FILE_EXPORT_TYPE, 
PR.FILE_RECORD_ID, 
PR.LAST_UPDTD_TS,
PR.VERSION_ID,
L.FILE_EXPORT_TYPE      AS LOCATION_FILE_EXPORT_TYPE, 
L.FILE_RECORD_ID        AS LOCATION_FILE_RECORD_ID, 
L.VERSION_ID            AS LOCATION_VERSION_ID, 
L.LAST_UPDTD_TS         AS LOCATION_LAST_UPDTD_TS, 
P.PLAN_PROV_ID          AS PLAN_PROV_ID ,
P.NATIONAL_PROV_ID      AS NATIONAL_PROV_ID,
P.PROV_MASTER_ID        AS PROV_MASTER_ID,
L.PROVIDER_LOCATION_MASTER_IDENTIFIER, 
ORG.PROV_ORGANIZATION_NAME AS PROV_ORGANIZATION_NAME,
P.PROV_LAST_NAME,
P.PROV_FIRST_NAME,
P.PROV_MIDDLE_INITIAL, 
P.PROV_NAME_SUFFIX,
PR.PROV_TYPE_CD,
PR.PROV_TYPE_DISPLAY,
--P.PROV_CREDENTIAL,
PQ.PROV_CREDENTIAL||'-'||PQ.PROV_CREDENTIAL_DISPLAY AS PROV_CREDENTIAL,
PR.SPECIALTY_DISPLAY AS SPECIALY_DISPLAY,
PR.PROV_ENTITY_TYPE_CD,
PR.PROV_ENTITY_TYPE_DISPLAY,
PR.PROV_EFF_DT,
PR.PROV_TERM_DT,
PR.PROV_CONTRACT_STATUS,
PR.ACCEPTING_NEW_PATIENTS_CD,
L.PROV_DBA_NAME         AS LOCATION_PROV_DBA_NAME,
L.PROV_ADDR_COUNTRY     AS LOCATION_PROV_ADDR_COUNTRY, 
L.PROV_ADDR_DISTRICT    AS LOCATION_PROV_ADDR_DISTRICT, 
L.PROV_ADDR_LINE1       AS LOCATION_PROV_ADDR_LINE1, 
L.PROV_ADDR_LINE2       AS LOCATION_PROV_ADDR_LINE2, 
L.PROV_ADDR_CITY        AS LOCATION_PROV_ADDR_CITY, 
L.PROV_ADDR_STATE       AS LOCATION_PROV_ADDR_STATE, 
L.PROV_ADDR_POSTALCD    AS LOCATION_PROV_ADDR_POSTAL_CD,
L.PROV_ADDR_USE         AS LOCATION_PROV_ADDR_USE,
PR.DISPLAY_IND_PROV,
PR.PROV_AFFIL_TYPE,
'' AS HOSPITAL_AFFIL_TYPE,
PR.PROV_AFFIL_REF AS PROV_AFFIL_NBR , 
'' AS HOSPITAL_AFFIL_NBR  ,
L.PROV_COMMUNICATION_INFO_PHONE,
--'' AS PROV_CLINIC_NUMBER,
ORG.PLAN_PROV_ID AS PROV_CLINIC_NUMBER,
LD.PLAN_CD,
LD.PLAN_CD_DESC,
ND.PRODUCT_ID               AS NETWORK_ID,
ND.PRODUCT_ID_DESC          AS NETWORK_NAME,
ND.PROV_PRODUCT_TYPE_CD     AS PRODUCT_TYPE,
ND.PRODUCT_CD               AS PRODUCT_ID,
ND.PRODUCT_CD_DESC          AS PRODUCT_NAME,
ND.PERIOD_START             AS NETWORK_EFF_DT,
ND.PERIOD_END               AS NETWORK_TERM_DT,
CASE WHEN CURRENT_DATE BETWEEN ND.PERIOD_START AND ND.PERIOD_END THEN 'A' ELSE 'T' END AS NETWORK_STATUS,
NVL(TX_ID.PROV_TAX_ID, P.PROV_TAX_ID )              AS PROV_TAX_ID,
NVL(TX_ID.PROV_TAX_ID_TYPE ,P.PROV_TAX_ID_TYPE)        AS PROV_TAX_ID_TYPE,
   TXNMY.TAXONOMY_CD_1          AS  TAXONOMY_CD_1,
   TXNMY.TAXONOMY_DESC_1        AS  TAXONOMY_DESC_1,
   TXNMY.TAXONOMY_CD_2          AS  TAXONOMY_CD_2,
   TXNMY.TAXONOMY_DESC_2        AS  TAXONOMY_DESC_2,
   TXNMY.TAXONOMY_CD_3          AS  TAXONOMY_CD_3,
   TXNMY.TAXONOMY_DESC_3        AS  TAXONOMY_DESC_3,
   TXNMY.TAXONOMY_CD_4          AS  TAXONOMY_CD_4,
   TXNMY.TAXONOMY_DESC_4        AS  TAXONOMY_DESC_4,
   TXNMY.TAXONOMY_1_BOARD_CERTIFICATION  AS  TAXONOMY_1_BOARD_CERTIFICATION,
   TXNMY.TAXONOMY_2_BOARD_CERTIFICATION  AS  TAXONOMY_2_BOARD_CERTIFICATION,
   TXNMY.TAXONOMY_3_BOARD_CERTIFICATION  AS  TAXONOMY_3_BOARD_CERTIFICATION,
   TXNMY.TAXONOMY_4_BOARD_CERTIFICATION  AS  TAXONOMY_4_BOARD_CERTIFICATION,
   SUBSTR(SPLIT_PART(P.COMMUNICATION,'\n',1),1,20) AS PROVIDER_LANGUAGE_CODE_1,
   SUBSTR(SPLIT_PART(P.COMMUNICATION,'\n',2),1,20) AS PROVIDER_LANGUAGE_CODE_2,
   SUBSTR(SPLIT_PART(P.COMMUNICATION,'\n',3),1,20) AS PROVIDER_LANGUAGE_CODE_3,
   SUBSTR(SPLIT_PART(P.COMMUNICATION,'\n',4),1,20) AS PROVIDER_LANGUAGE_CODE_4,
   SUBSTR(SPLIT_PART(P.COMMUNICATION,'\n',5),1,20) AS PROVIDER_LANGUAGE_CODE_5,
   ''  AS PROVIDER_OFFICE_LANGUAGE_CODE_1,
   ''  AS PROVIDER_OFFICE_LANGUAGE_CODE_2,
   ''  AS PROVIDER_OFFICE_LANGUAGE_CODE_3,
   ''  AS PROVIDER_OFFICE_LANGUAGE_CODE_4,
   ''  AS PROVIDER_OFFICE_LANGUAGE_CODE_5,
L.PROV_DBA_NAME                         AS PROVIDERS_OFFICE_NAME,
L.PROV_COMMUNICATION_INFO_FAX           AS PROVIDERS_FAX_NUMBER, 
L.PROV_COMMUNICATION_INFO_URL           AS PROVIDER_WEB_ADDRESS,
SUBSTR(HCSVC.PROVIDER_CHARACTERISTICS_CODE_1,1,100)   AS PROVIDER_CHARACTERISTICS_CODE_1 ,
SUBSTR(HCSVC.PROVIDER_CHARACTERISTICS_CODE_2,1,100)   AS PROVIDER_CHARACTERISTICS_CODE_2 ,
SUBSTR(HCSVC.PROVIDER_CHARACTERISTICS_CODE_3,1,100)   AS PROVIDER_CHARACTERISTICS_CODE_3 ,
SUBSTR(HCSVC.PROVIDER_CHARACTERISTICS_CODE_4,1,100)   AS PROVIDER_CHARACTERISTICS_CODE_4 ,
PR.PCP_IND_CD                               AS  PCP_INDICATOR ,
PCP_SELECTABILITY_CD                        AS PCP_SELECTABILITY_INDICATOR,
ORG1.PROV_ORGANIZATION_NAME                 AS PROVIDER_MEDICAL_SCHOOL,
SUBSTR(P.PROV_MEDICAL_SCHOOL_YEAR,1,4)      AS PROVIDER_MEDICAL_SCHOOL_YEAR,
ORG2.PROV_ORGANIZATION_NAME                 AS PROVIDER_RESIDENCY,
ORG3.PROV_ORGANIZATION_NAME                 AS PROVIDER_INTERNSHIP,
PR.PATIENT_AGE_RANGE_LOW        AS PATIENT_AGE_FROM_RESTRICTION,
PR.PATIENT_AGE_RANGE_HIGH       AS PATIENT_AGE_TO_RESTRICTION,
PR.PROV_PATIENT_GENDER_LIMIT    AS PATIENT_GENDER_RESTRICTION,
L.service_area_cd               AS SERVICE_AREA_INDICATOR,
CASE WHEN PR.PROV_ACCEPTS_MEMBER_SELECT_ATTRIB_IND = 'false' THEN 'N' WHEN PR.PROV_ACCEPTS_MEMBER_SELECT_ATTRIB_IND = 'true' THEN  'Y' END AS PROV_ACCEPTS_MBR_SELF_ATTRB_IND,
NVL(PR.DAYS_OF_WEEK_AND_OFFICE_HOURS ,L.DAYS_OF_WEEK_AND_OFFICE_HOURS) AS DAYS_OF_WEEK_AND_OFFICE_HOURS,
SPLIT_PART(PR.VALUE_BASED_PROGRAM_ID , ' ',1)   AS  VALUE_BASED_PROGRAM_ID_1,
SPLIT_PART(PR.VALUE_BASED_PROGRAM_ID , ' ',2)   AS  VALUE_BASED_PROGRAM_ID_2,
SPLIT_PART(PR.VALUE_BASED_PROGRAM_ID , ' ',3)   AS  VALUE_BASED_PROGRAM_ID_3,
SPLIT_PART(PR.VALUE_BASED_PROGRAM_ID , ' ',4)   AS  VALUE_BASED_PROGRAM_ID_4,
P.CROSS_REFERENCE_PLAN_PROV_ID                  AS  PROVIDER_CROSS_REFERENCE_NUMBER,
PNR.STATE_TERRITORY                 AS STATE_TERRITORY,
PNR.AWAY_FROM_HOME_CARE_IND         AS AWAY_FROM_HOME_CARE_IND ,
PNR.BLUE_CARD_IND                   AS BLUE_CARD_IND ,
PNR.MEDICARE_ADV_PPO_IND            AS MEDICARE_ADV_PPO_IND ,
PNR.FEP_IND                         AS FEP_IND ,
PNR.BLUE_SELECT_IND                 AS BLUE_SELECT_IND ,
PNR.BLUE_HIGH_PERFORMENCE_IND       AS BLUE_HIGH_PERFORMENCE_IND ,
PNR.BCBS_AXIS_COST_DATA_IND         AS BCBS_AXIS_COST_DATA_IND ,
CURRENT_DATE                        AS LOAD_DT,


P.PROV_GENDER           AS PROV_GENDER,
P.BIRTH_DT              AS BIRTH_DT,
L.PROV_TERMINATION_CD   AS PROV_TERMINATION_CD,
COUNTY.COUNTY_NAME      AS COUNTY_NAME,
COALESCE(PE1.EMAIL,PE2.EMAIL,PE3.EMAIL)                    AS PROV_EMAIL,
TO_VARCHAR(PQ1.PROV_LICENSES)       AS PROV_LICENSE_NBR


FROM    PDT_FHIR_PRACTITIONER_ROLE_TEMP  PR       
JOIN    ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_PRACTITIONER P           ON PR.PRACTITIONER_REF_RECORD_ID = P.FILE_RECORD_ID AND PR.FILE_EXPORT_TYPE = P.FILE_EXPORT_TYPE AND PR.FILE_EXPORT_TYPE = '${BCBSA_FILE_EXPORT_TYPE}' 
LEFT JOIN    (SELECT DISTINCT PLAN_CD,PLAN_CD_DESC   FROM ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_LICENSEE_DIM) LD      ON SUBSTR(P.FILE_RECORD_ID,1,3) = LD.PLAN_CD 
LEFT JOIN    (SELECT DISTINCT ORGANIZATION_ID,PRODUCT_ID, PRODUCT_ID_DESC, PROV_PRODUCT_TYPE_CD,PRODUCT_CD, PRODUCT_CD_DESC, PERIOD_START, PERIOD_END  FROM ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_NETWORK_DIM) ND ON PR.NETWORK_REF_RECORD_ID = ND.ORGANIZATION_ID
LEFT JOIN    (SELECT DISTINCT NETWORK_ID,PRODUCT_ID, STATE_TERRITORY,AWAY_FROM_HOME_CARE_IND,BLUE_CARD_IND,MEDICARE_ADV_PPO_IND,FEP_IND,BLUE_SELECT_IND,BLUE_HIGH_PERFORMENCE_IND,BCBS_AXIS_COST_DATA_IND FROM  ${SNOWFLAKE_ENV}_CDW_DB.REF.PROV_NET_PRODUCT_REF) PNR ON ND.PRODUCT_ID = PNR.NETWORK_ID AND ND.PRODUCT_CD = PNR.PRODUCT_ID
LEFT JOIN    (PDT_FHIR_PRACTITIONER_TAXONOMY_FINAL) TXNMY   ON  TXNMY.FILE_RECORD_ID = P.FILE_RECORD_ID AND TXNMY.FILE_EXPORT_TYPE = P.FILE_EXPORT_TYPE
LEFT JOIN PROV_TAX_ID TX_ID ON TX_ID.FILE_RECORD_ID = P.FILE_RECORD_ID
LEFT JOIN ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_LOCATION L     ON PR.LOCATION_REF_RECORD_ID = L.FILE_RECORD_ID     AND PR.FILE_EXPORT_TYPE = L.FILE_EXPORT_TYPE
LEFT JOIN HLT_CARE_SVC_FINAL HCSVC ON PR.FILE_RECORD_ID =  HCSVC.FILE_RECORD_ID
LEFT JOIN FHIR_ORG_NAME ORG ON  ORG.FILE_RECORD_ID  = PR.ORGANIZATION_REF_RECORD_ID
LEFT JOIN FHIR_ORG_NAME ORG1 ON ORG1.FILE_RECORD_ID =  P.PROV_MEDICAL_SCHOOL         
LEFT JOIN FHIR_ORG_NAME ORG2 ON ORG2.FILE_RECORD_ID =  P.PROV_RESIDENCY        
LEFT JOIN FHIR_ORG_NAME ORG3 ON ORG3.FILE_RECORD_ID =  P.PROV_INTERNSHIP  
LEFT JOIN (SELECT DISTINCT FILE_RECORD_ID , PROV_CREDENTIAL, PROV_CREDENTIAL_DISPLAY FROM   PROV_QUAL WHERE PROV_CREDENTIAL_EXTENSION_CODE = 'degree' )  PQ ON PR.PRACTITIONER_REF_RECORD_ID = PQ.FILE_RECORD_ID   
LEFT JOIN (SELECT STATE_CD, ZIP_CD,COUNTY_NAME  FROM ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_ST_COUNTY_ZIP_DIM QUALIFY ROW_NUMBER() OVER(PARTITION BY ZIP_CD  ORDER BY VERSION_ID DESC) = 1) COUNTY ON SUBSTR(COUNTY.ZIP_CD,1,5) = SUBSTR(L.PROV_ADDR_POSTALCD,1,5) AND COUNTY.STATE_CD = L.PROV_ADDR_STATE

LEFT JOIN PROV_QUAL_1 PQ1 ON PQ1.FILE_RECORD_ID =  PR.PRACTITIONER_REF_RECORD_ID

LEFT JOIN PROV_EMAIL PE1 ON PE1.FILE_RECORD_ID = PR.PRACTITIONER_REF_RECORD_ID 
LEFT JOIN PROV_EMAIL PE2 ON PE2.FILE_RECORD_ID = PR.FILE_RECORD_ID 
LEFT JOIN PROV_EMAIL PE3 ON PE3.FILE_RECORD_ID = PR.LOCATION_REF_RECORD_ID 

WHERE PR.FILE_EXPORT_TYPE = '${BCBSA_FILE_EXPORT_TYPE}' ;


INSERT INTO ${SNOWFLAKE_ENV}_DATAMART_DB.PROV.BCBSA_PDT_PROV_HIST  (SELECT DISTINCT *FROM BCBSA_PDT_PROV_HIST_TEMP1);



CREATE OR REPLACE TEMPORARY TABLE ORG_HLT_CARE_SVC AS 
SELECT PR.FILE_RECORD_ID AS FILE_RECORD_ID , HC.healthcare_service_type_cd ||':'|| HC.healthcare_service_type AS HLT_CARE_SVC_CD,
ROW_NUMBER() OVER (PARTITION BY PR.file_record_id  ORDER BY HC.file_record_id DESC ) AS ROW_NUM
FROM ( SELECT DISTINCT FILE_RECORD_ID, HEALTHCARE_SERVICE_REF_RECORD_ID, FILE_EXPORT_TYPE FROM  
       ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_ORGANIZATION_AFFLIATION  WHERE FILE_EXPORT_TYPE = '${BCBSA_FILE_EXPORT_TYPE}') PR 
JOIN ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_HEALTHCARE_SERVICE HC 
ON  PR.FILE_EXPORT_TYPE = HC.FILE_EXPORT_TYPE AND PR.HEALTHCARE_SERVICE_REF_RECORD_ID = HC.FILE_RECORD_ID AND healthcare_service_type IS NOT NULL  
AND healthcare_service_type <> ''  QUALIFY  ROW_NUM <=4;


CREATE OR REPLACE TEMPORARY TABLE ORG_HLT_CARE_SVC_FINAL AS  
SELECT 
$1 AS FILE_RECORD_ID,
$2 AS PROVIDER_CHARACTERISTICS_CODE_1,
$3 AS PROVIDER_CHARACTERISTICS_CODE_2,
$4 AS PROVIDER_CHARACTERISTICS_CODE_3,
$5 AS PROVIDER_CHARACTERISTICS_CODE_4
FROM ORG_HLT_CARE_SVC PIVOT(MAX(HLT_CARE_SVC_CD) FOR ROW_NUM IN (1,2,3,4))  ;



CREATE OR REPLACE TEMPORARY TABLE BCBSA_PDT_PROV_HIST_TEMP2 AS 
SELECT  DISTINCT 
O.FILE_EXPORT_TYPE, 
O.FILE_RECORD_ID,
O.LAST_UPDTD_TS, 
O.VERSION_ID,
L.FILE_EXPORT_TYPE      AS LOCATION_FILE_EXPORT_TYPE, 
L.FILE_RECORD_ID        AS LOCATION_FILE_RECORD_ID, 
L.VERSION_ID            AS LOCATION_VERSION_ID, 
L.LAST_UPDTD_TS         AS LOCATION_LAST_UPDTD_TS,
O.PLAN_PROV_ID          AS PLAN_PROV_ID,
SUBSTR(O.NATIONAL_PROV_ID_LIST,1,4950)  AS NATIONAL_PROV_ID, 
O.PROV_MASTER_ID        AS PROV_MASTER_ID,
L.PROVIDER_LOCATION_MASTER_IDENTIFIER,
O.PROV_ORGANIZATION_NAME,
'' AS PROV_LAST_NAME,
'' AS PROV_FIRST_NAME,
'' AS PROV_MIDDLE_INITIAL, 
'' AS PROV_NAME_SUFFIX, 
OA.PROV_TYPE_CD AS PROV_TYPE_CD,
OA.PROV_TYPE_DISPLAY AS PROV_TYPE_DISPLAY,
'' AS PROV_CREDENTIAL,
'' AS SPECIALY_DISPLAY,
OA.PROV_ENTITY_TYPE_CD AS PROV_ENTITY_TYPE_CD,
OA.PROV_ENTITY_TYPE_DISPLAY AS PROV_ENTITY_TYPE_DISPLAY,
OA.PROV_EFF_DT AS PROV_EFF_DT,
OA.PROV_TERM_DT AS PROV_TERM_DT,
OA.PROV_CONTRACT_STATUS AS PROV_CONTRACT_STATUS,
'' AS ACCEPTING_NEW_PATIENTS_CD,
    L.PROV_DBA_NAME         AS LOCATION_PROV_DBA_NAME,
    L.PROV_ADDR_COUNTRY     AS LOCATION_PROV_ADDR_COUNTRY, 
    L.PROV_ADDR_DISTRICT    AS LOCATION_PROV_ADDR_DISTRICT, 
    L.PROV_ADDR_LINE1       AS LOCATION_PROV_ADDR_LINE1, 
    L.PROV_ADDR_LINE2       AS LOCATION_PROV_ADDR_LINE2, 
    L.PROV_ADDR_CITY        AS LOCATION_PROV_ADDR_CITY, 
    L.PROV_ADDR_STATE       AS LOCATION_PROV_ADDR_STATE, 
    L.PROV_ADDR_POSTALCD    AS LOCATION_PROV_ADDR_POSTALCD,
    L.PROV_ADDR_USE         AS LOCATION_PROV_ADDR_USE,
   OA.DISPLAY_IND_PROV      AS DISPLAY_IND_PROV,
''      AS PROV_AFFIL_TYPE,
SPLIT_PART(OA.PROV_AFFLIATION_TYPE,':',1) AS HOSPITAL_AFFIL_TYPE,
''  AS PROV_AFFIL_NBR ,
SPLIT_PART(OA.PROV_AFFLIATION_TYPE,':',2) AS HOSPITAL_AFFIL_NBR ,
L.PROV_COMMUNICATION_INFO_PHONE,
'' AS PROV_CLINIC_NUMBER,
LD.PLAN_CD,
LD.PLAN_CD_DESC,
ND.PRODUCT_ID AS NETWORK_ID,
ND.PRODUCT_ID_DESC AS NETWORK_NAME,
ND.PROV_PRODUCT_TYPE_CD AS PRODUCT_TYPE,
ND.PRODUCT_CD AS PRODUCT_ID,
ND.PRODUCT_CD_DESC AS PRODUCT_NAME,
ND.PERIOD_START AS NETWORK_EFF_DT,
ND.PERIOD_END AS NETWORK_TERM_DT,
CASE WHEN CURRENT_DATE BETWEEN ND.PERIOD_START AND ND.PERIOD_END THEN 'A' ELSE 'T' END AS NETWORK_STATUS,
O.PROV_TAX_ID AS PROV_TAX_ID,
O.PROV_TAX_ID_TYPE AS PROV_TAX_ID_TYPE,
    ' ' AS TAXONOMY_CD_1,        
    ' ' AS TAXONOMY_DESC_1,
    ' ' AS TAXONOMY_CD_2,
    ' ' AS TAXONOMY_DESC_2,
    ' ' AS TAXONOMY_CD_3,
    ' ' AS TAXONOMY_DESC_3,
    ' ' AS TAXONOMY_CD_4,
    ' ' AS TAXONOMY_DESC_4,
    ' ' AS TAXONOMY_1_BOARD_CERTIFICATION,
    ' ' AS TAXONOMY_2_BOARD_CERTIFICATION,
    ' ' AS TAXONOMY_3_BOARD_CERTIFICATION,
    ' ' AS TAXONOMY_4_BOARD_CERTIFICATION,
      ' '  AS  PROVIDER_LANGUAGE_CODE_1,
      ' '  AS  PROVIDER_LANGUAGE_CODE_2,
      ' '  AS  PROVIDER_LANGUAGE_CODE_3,
      ' '  AS  PROVIDER_LANGUAGE_CODE_4,
      ' '  AS  PROVIDER_LANGUAGE_CODE_5,
      SUBSTR(SPLIT_PART(L.PROV_STAFF_LANGUAGE,'\n',1),1,20)   AS  PROVIDER_OFFICE_LANGUAGE_CODE_1,
      SUBSTR(SPLIT_PART(L.PROV_STAFF_LANGUAGE,'\n',2),1,20)   AS  PROVIDER_OFFICE_LANGUAGE_CODE_2,
      SUBSTR(SPLIT_PART(L.PROV_STAFF_LANGUAGE,'\n',3),1,20)   AS  PROVIDER_OFFICE_LANGUAGE_CODE_3,
      SUBSTR(SPLIT_PART(L.PROV_STAFF_LANGUAGE,'\n',4),1,20)   AS  PROVIDER_OFFICE_LANGUAGE_CODE_4,
      SUBSTR(SPLIT_PART(L.PROV_STAFF_LANGUAGE,'\n',5),1,20)   AS  PROVIDER_OFFICE_LANGUAGE_CODE_5,
      L.PROV_DBA_NAME                         AS PROVIDERS_OFFICE_NAME,
      L.PROV_COMMUNICATION_INFO_FAX           AS PROVIDERS_FAX_NUMBER, 
      L.PROV_COMMUNICATION_INFO_URL           AS PROVIDER_WEB_ADDRESS,
SUBSTR(HCSVC.PROVIDER_CHARACTERISTICS_CODE_1,1,100)   AS PROVIDER_CHARACTERISTICS_CODE_1 ,
SUBSTR(HCSVC.PROVIDER_CHARACTERISTICS_CODE_2,1,100)   AS PROVIDER_CHARACTERISTICS_CODE_2 ,
SUBSTR(HCSVC.PROVIDER_CHARACTERISTICS_CODE_3,1,100)   AS PROVIDER_CHARACTERISTICS_CODE_3 ,
SUBSTR(HCSVC.PROVIDER_CHARACTERISTICS_CODE_4,1,100)   AS PROVIDER_CHARACTERISTICS_CODE_4 ,
     ' '  AS PCP_INDICATOR,
     OA.PCP_SELECTABILITY_CD  AS PCP_SELECTABILITY_INDICATOR,
     ' '  AS PROVIDER_MEDICAL_SCHOOL,
     ' '  AS PROVIDER_MEDICAL_SCHOOL_YEAR,
     ' '  AS PROVIDER_RESIDENCY,
     ' '  AS PROVIDER_INTERNSHIP,
     ' '  AS PATIENT_AGE_FROM_RESTRICTION,
     ' '  AS PATIENT_AGE_TO_RESTRICTION,
     ' '  AS PATIENT_GENDER_RESTRICTION,
     ' '  AS SERVICE_AREA_INDICATOR,
     ' '  AS PROV_ACCEPTS_MBR_SELF_ATTRB_IND,
     ' '  AS DAYS_OF_WEEK_AND_OFFICE_HOURS,
SPLIT_PART(OA.VALUE_BASED_PROGRAM_ID_LIST , ' ',1)   AS  VALUE_BASED_PROGRAM_ID_1,
SPLIT_PART(OA.VALUE_BASED_PROGRAM_ID_LIST , ' ',2)   AS  VALUE_BASED_PROGRAM_ID_2,
SPLIT_PART(OA.VALUE_BASED_PROGRAM_ID_LIST , ' ',3)   AS  VALUE_BASED_PROGRAM_ID_3,
SPLIT_PART(OA.VALUE_BASED_PROGRAM_ID_LIST , ' ',4)   AS  VALUE_BASED_PROGRAM_ID_4,
    O.CROSS_REFERENCE_PLAN_PROV_ID  AS PROVIDER_CROSS_REFERENCE_NUMBER,
PNR.STATE_TERRITORY                 AS STATE_TERRITORY,
PNR.AWAY_FROM_HOME_CARE_IND         AS AWAY_FROM_HOME_CARE_IND ,
PNR.BLUE_CARD_IND                   AS BLUE_CARD_IND ,
PNR.MEDICARE_ADV_PPO_IND            AS MEDICARE_ADV_PPO_IND ,
PNR.FEP_IND                         AS FEP_IND ,
PNR.BLUE_SELECT_IND                 AS BLUE_SELECT_IND ,
PNR.BLUE_HIGH_PERFORMENCE_IND       AS BLUE_HIGH_PERFORMENCE_IND ,
PNR.BCBS_AXIS_COST_DATA_IND         AS BCBS_AXIS_COST_DATA_IND ,
CURRENT_DATE AS LOAD_DT,
' ' AS PROV_GENDER,
NULL AS BIRTH_DT,
L.PROV_TERMINATION_CD AS PROV_TERMINATION_CD,
COUNTY.COUNTY_NAME  AS COUNTY_NAME,
' ' AS PROV_EMAIL,
' ' AS PROV_LICENSE_NBR


FROM   ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_ORGANIZATION O 
JOIN  ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_ORGANIZATION_AFFLIATION OA ON OA.PARTICIPATING_ORGANIZATION_REF_RECORD_ID = O.FILE_RECORD_ID AND OA.FILE_EXPORT_TYPE = O.FILE_EXPORT_TYPE
JOIN   (SELECT DISTINCT INSURANCE_LICENSEE_ID,  PLAN_CD,PLAN_CD_DESC   FROM ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_LICENSEE_DIM) LD    ON  LD.INSURANCE_LICENSEE_ID = OA.licensee_ref_record_id
JOIN  ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_NETWORK_DIM ND ON OA.NETWORK_REF_RECORD_ID = ND.ORGANIZATION_ID
LEFT JOIN    (SELECT DISTINCT NETWORK_ID,PRODUCT_ID, STATE_TERRITORY,AWAY_FROM_HOME_CARE_IND,BLUE_CARD_IND,MEDICARE_ADV_PPO_IND,FEP_IND,
            BLUE_SELECT_IND,BLUE_HIGH_PERFORMENCE_IND,BCBS_AXIS_COST_DATA_IND FROM  ${SNOWFLAKE_ENV}_CDW_DB.REF.PROV_NET_PRODUCT_REF) PNR 
ON ND.PRODUCT_ID = PNR.NETWORK_ID AND ND.PRODUCT_CD = PNR.PRODUCT_ID

LEFT JOIN ORG_HLT_CARE_SVC_FINAL HCSVC          ON OA.FILE_RECORD_ID =  HCSVC.FILE_RECORD_ID
LEFT JOIN ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_LOCATION L             ON OA.LOCATION_REF_RECORD_ID = L.FILE_RECORD_ID     AND OA.FILE_EXPORT_TYPE = L.FILE_EXPORT_TYPE
LEFT JOIN (SELECT STATE_CD, ZIP_CD,COUNTY_NAME  FROM ${SNOWFLAKE_ENV}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_ST_COUNTY_ZIP_DIM QUALIFY ROW_NUMBER() OVER(PARTITION BY ZIP_CD  ORDER BY VERSION_ID DESC) = 1) COUNTY ON SUBSTR(COUNTY.ZIP_CD,1,5) = SUBSTR(L.PROV_ADDR_POSTALCD,1,5) AND COUNTY.STATE_CD = L.PROV_ADDR_STATE

WHERE O.FILE_EXPORT_TYPE = '${BCBSA_FILE_EXPORT_TYPE}'  ;


INSERT INTO ${SNOWFLAKE_ENV}_DATAMART_DB.PROV.BCBSA_PDT_PROV_HIST  (SELECT DISTINCT * FROM BCBSA_PDT_PROV_HIST_TEMP2);