
CREATE OR REPLACE TASK {{env}}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_INSURANCE_PLAN_LOAD_DAILY_TASK
WAREHOUSE = {{env}}_ELT_SML_WH
--SCHEDULE  = 'USING CRON 0 2 * * * America/Chicago'
AFTER  {{env}}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_LOAD_DAILY_TASK
AS 

  BEGIN 
   
   USE DATABASE {{env}}_RAW_INBOUND_DB;
   USE SCHEMA BCBSA; 

   CREATE OR REPLACE TEMPORARY TABLE PDT_FHIR_INSURANCE_PLAN_TEMP LIKE  PDT_FHIR_INSURANCE_PLAN;


INSERT INTO PDT_FHIR_INSURANCE_PLAN_TEMP(
    FILE_EXPORT_TYPE
    ,FILE_RECORD_ID
    ,VERSION_ID
    ,LAST_UPDTD_TS
    ,ADMINISTERED_BY_REF_RECORD_ID
    ,NETWORK_REF_RECORD_ID
    ,DESCRIPTIVE_PRODUCT_NAME
    ,PROGRAM_AFFIL_TYPE_CD
    ,PROGRAM_AFFIL_TYPE
    ,BCBS_PRODUCT_TYPE_CD
    ,BCBS_PRODUCT_TYPE
    ,MEMPREFIX
    ,PROFILE_TYPE
    ,LOAD_DT
    )

WITH MAX_PDT_REC AS (SELECT FILE_RECORD_ID , SPLIT_PART(FILE_NAME,'/',3)  AS FILE_EXPORT_TYPE, MAX(FILE_LAST_MODIFIED) AS FILE_LAST_MODIFIED  FROM PDT_FHIR 
WHERE  FILE_RESOURCE_TYPE='InsurancePlan' 
GROUP BY FILE_RECORD_ID, SPLIT_PART(FILE_NAME,'/',3))

SELECT 
 FILE_EXPORT_TYPE
,FILE_RECORD_ID
,MAX(VERSION_ID) AS VERSION_ID
,MAX(LAST_UPDTD) AS LAST_UPDTD_TS
,MAX(administeredBy_reference) AS ADMINISTERED_BY_REF_RECORD_ID
,network_reference AS NETWORK_REF_RECORD_ID
,MAX(Descriptive_Product_Name) AS DESCRIPTIVE_PRODUCT_NAME
,MAX(ProgramAffiliationType_code ) AS PROGRAM_AFFIL_TYPE_CD
,MAX(ProgramAffiliationType) PROGRAM_AFFIL_TYPE
,MAX(BCBSProductType_code) AS BCBS_PRODUCT_TYPE_CD
,MAX(BCBSProductType) AS BCBS_PRODUCT_TYPE
,MAX(memprefix) AS MEMPREFIX
,MAX(PROFILE_TYPE) AS PROFILE_TYPE
,LOAD_DT
FROM 
(
SELECT 

  SPLIT_PART(FILE_NAME,'/',3) AS FILE_EXPORT_TYPE
,A.FILE_RECORD_ID
,FILE_CONTENT_RAW:meta:versionId AS VERSION_ID
,FILE_CONTENT_RAW:meta:lastUpdated AS LAST_UPDTD
,FILE_CONTENT_RAW:name AS Descriptive_Product_Name
,SPLIT_PART(FILE_CONTENT_RAW:administeredBy:reference,'/',-1) AS administeredBy_reference
,SPLIT_PART(network.value:reference,'/',-1) AS network_reference 
   
   
,CASE WHEN (SPLIT_PART(type_coding.value:system,'/',-1) = 'BCBSProgramAffiliationTypeCS' ) THEN type_coding.value:code else '' END AS  ProgramAffiliationType_code
,CASE WHEN (SPLIT_PART(type_coding.value:system,'/',-1) = 'BCBSProgramAffiliationTypeCS' ) THEN type_coding.value:display else '' END AS  ProgramAffiliationType

,CASE WHEN (SPLIT_PART(type_coding.value:system,'/',-1) = 'BCBSProductTypeCS' ) THEN type_coding.value:code else '' END AS  BCBSProductType_code
,CASE WHEN (SPLIT_PART(type_coding.value:system,'/',-1) = 'BCBSProductTypeCS' ) THEN type_coding.value:display else '' END AS  BCBSProductType
  
,CASE WHEN (SPLIT_PART(extension.value:url,'/',-1) = 'memprefix' ) THEN extension.value:valueString else '' END AS  memprefix  
,split_part(FILE_CONTENT_RAW:id,'-',-1) AS PROFILE_TYPE
,LOAD_DT
FROM "BCBSA"."PDT_FHIR"  A ,MAX_PDT_REC B
,lateral flatten(input=>FILE_CONTENT_RAW:type,outer=>true) type
,lateral flatten(input=>FILE_CONTENT_RAW:extension,outer=>true) extension
,lateral flatten(input=>type.value:coding,outer=>true) type_coding
,lateral flatten(input=>FILE_CONTENT_RAW:network,outer=>true) network
WHERE FILE_RESOURCE_TYPE='InsurancePlan' 
AND A.FILE_RECORD_ID = B.FILE_RECORD_ID AND A.FILE_LAST_MODIFIED = B.FILE_LAST_MODIFIED AND SPLIT_PART(A.FILE_NAME,'/',3) =B.FILE_EXPORT_TYPE
AND LOAD_DT IN ( SELECT DISTINCT LOAD_DT FROM PDT_FHIR MINUS  SELECT DISTINCT LOAD_DT FROM PDT_FHIR_INSURANCE_PLAN )
)
  
GROUP BY   FILE_EXPORT_TYPE
,FILE_RECORD_ID, network_reference,LOAD_DT;



MERGE INTO PDT_FHIR_INSURANCE_PLAN PR
USING PDT_FHIR_INSURANCE_PLAN_TEMP PR_TEMP ON  TRIM(PR.FILE_RECORD_ID) = TRIM(PR_TEMP.FILE_RECORD_ID) AND TRIM(PR.FILE_EXPORT_TYPE) = TRIM(PR_TEMP.FILE_EXPORT_TYPE)
WHEN MATCHED THEN DELETE; 

INSERT INTO PDT_FHIR_INSURANCE_PLAN  (SELECT * FROM PDT_FHIR_INSURANCE_PLAN_TEMP);

   END;

ALTER TASK {{env}}_RAW_INBOUND_DB.BCBSA.PDT_FHIR_INSURANCE_PLAN_LOAD_DAILY_TASK RESUME;
